fix(YALB-1588): remove old files before unzipping
When exporting, there may be a case where we have an asset or node that
no longer should exist.  Do accomodate this, we remove all files in the
directory so we can unzip them fresh.

We add some safety input controls here because we do not want to delete
folders that would harm their system, like if someone accidentally put /
or ~.  So we now have a prompt to ensure they want to delete all files
within the directory specified so that they can choose to cancel at that
time.

diff --git a/scripts/local/starterkit/create-export b/scripts/local/starterkit/create-export
--- a/scripts/local/starterkit/create-export
+++ b/scripts/local/starterkit/create-export
@@ -81,10 +81,25 @@ retrieveFileFromSftp() {
 EOF
 }
 
+# Remove all files in the destination location before unzipping.
+# The reasoning is that we don't want lingering yml files from nodes
+# we might have deleted since the last export.
+removeCurrentFilesInGitRepo() {
+    read -rp "Are you sure you want to delete the contents of $1? (y/n) " answer
+
+    if [ "$answer" != "y" ]; then
+        echo "Aborting."
+        exit 1
+    fi
+
+    rm -rf "${1:?}"/*
+}
+
 # Unzips the folder to another location so that we can update the git repo.
 unzipToFolder() {
     createFolderIfNotExists "$2"
     if [[ -d "$2" ]]; then
+        removeCurrentFilesInGitRepo "$2"
         unzip -o "$1" -d "$2"
     else
         echo "Folder $2 does not exist and could not create it.  Please see why."
